bookslibraryapp/urls.py
from django.urls import path
from . import views
app_name='bookslibraryapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('books/<int:books_id>/',views.detail,name='detail'),
    path('add/',views.add_books,name='add_books'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

bookslibraryproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bookslibraryapp.urls"))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookslibraryapp/models.py
from django.db import models
# Create your models here.
class Books(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

bookslibraryapp/forms.py
from django import forms
from . models import Books

class BooksForm(forms.ModelForm):
    class Meta:
        model=Books
        fields=['name','desc','year','img']

bookslibraryapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from . models import Books
from . forms import BooksForm

# Create your views here.
def index(request):

   books=Books.objects.all()
   context={
       'books_list':books
   }
   return render(request,'index.html',context)
def detail(request,books_id):
    books=Books.objects.get(id=books_id)
    return render(request,"detail.html",{'books':books})

def add_books(request):
    if request.method =="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        books=Books(name=name,desc=desc,year=year,img=img)
        books.save()

    return render(request,'add.html')

def update(request,id):
    books=Books.objects.get(id=id)
    form=BooksForm(request.POST or None,request.FILES,instance=books)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'books':books})

def delete(request,id):
    if request.method=='POST':
        books=Books.objects.get(id=id)

        books.delete()
        return redirect('/')

    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  <input type="text" name="name" placeholder="Enter the book name">
  <input type="text" name="desc" placeholder="Enter your book description">
  <input type="text" name="year" placeholder="Enter your published year">
  <input type="file" name="img" placeholder="enter the image">
  <input type="submit">



</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body><!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
     Online Books Library
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">

    {% csrf_token %}
    Are you sure to delete this book?
    <input type="submit">
</form>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{books.img.url}}" width="500" height="600">
        </div>

        <div class="col-md-6">
        <h1>{{books.name}}</h1>
        <h3>{{books.desc}}</h3>
        <h4>{{books.year}}</h4>
        <a class="btn btn-warning" href="{% url 'bookslibraryapp:update' books.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'bookslibraryapp:delete' books.id %}">delete</a><br>

        </div>
    </div>
</div>





{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">

        {% for i in Books_list %}
        <div class="col-md-4">
        <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="" height="400">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.price}}</p>
    <a href="{% url 'bookslibraryapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
        </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}